### ISSUE TITLE
Incompatibility - Wacky Responses.

### ISSUE THREAD

**Issue by nanepiwo** [kaeza/minetest-irc#16]
Some commands are wacky with how they respond. "cmd seen" and "cmd who" do not work. "cmd mail" from the chatplus mod shows a confirmation in a private message window even if the command was induced in the public chat. I'm not sure if this belongs in the same issue, but "(timed out)" does not display on quit messages which have this in-game. All this has been tested in Craig's Server (#minetest-craig on InchraNet) and might not apply universally.

**Comment by ShadowNinja** [comment]
This is an issue with https://github.com/ShadowNinja/minetest-irc_commands.

This happens because some mods use `chat_send_player` rather than chat command return values.  `irc_commands` can't tell if the message is supposed to be public or private, so it makes a safe guess.

Ask mod makers to use chat command return values in their mods.
